<?php

declare(strict_types=1);

namespace App\Support\PasswordScheme;

/**
 * Dovecot's salted digest family — SSHA, SSHA256, SSHA512.
 *
 * The stored value is base64 of the raw digest followed by the salt. The
 * digest length is fixed per algorithm, so the salt is whatever follows it,
 * and its length is not recorded anywhere: it is derived on read. That is why
 * a hash generated by any iRedMail install verifies here regardless of the
 * salt length that install chose.
 */
final class SaltedDigestScheme implements Scheme
{
    public function __construct(
        private readonly string $label,
        private readonly string $algorithm,
        private readonly int $digestLength,
        private readonly int $saltLength = 8,
    ) {}

    public function name(): string
    {
        return $this->label;
    }

    public function handles(string $storedWithoutPrefix): bool
    {
        $decoded = base64_decode($storedWithoutPrefix, true);

        return $decoded !== false && strlen($decoded) > $this->digestLength;
    }

    public function verify(string $plain, string $storedWithoutPrefix): bool
    {
        $decoded = base64_decode($storedWithoutPrefix, true);

        if ($decoded === false || strlen($decoded) <= $this->digestLength) {
            return false;
        }

        $digest = substr($decoded, 0, $this->digestLength);
        $salt = substr($decoded, $this->digestLength);

        return hash_equals($digest, hash($this->algorithm, $plain.$salt, true));
    }

    public function hash(string $plain): string
    {
        $salt = random_bytes($this->saltLength);

        return base64_encode(hash($this->algorithm, $plain.$salt, true).$salt);
    }

    public function isSafeToGenerate(): bool
    {
        return true;
    }
}
